### PR TITLE
Coding introduction

### PR DESCRIPTION
**Pull request by ipa-mig**
This is an introduction to the workflow at IPA for using ROS, with special sections on ROS (general), GIT and compilation.
Mainly it is a list of links, small guide lines and ideas, that I feel are good to know.
Check the markdown version [**here**](https://github.com/ipa-mig/setup/blob/coding_introduction/coding_introduction/CodingIntroduction.md)

Initial discussion for reference [here](https://github.com/ipa-mig/setup/pull/1).

@ipa-fxm @ipa-mdl @ipa-srd @ipa-fmw @ipa-flg @ipa-frm

### CODE REVIEW

**Comment by ipa-fxm** [comment]
As my input was considered: LGTM
@ipa-mig Thanks for this comprehensive document!

**Comment by ipa-nhg** [comment]
Great!! :+1: 
LGTM, but maybe we can move this documentation to a more accessible link ( 
https://github.com/ipa-mig/setup/blob/coding_introduction/coding_introduction/CodingIntroduction.md )?

**Comment by ipa-mig** [comment]
Sure. What do you propose?

**Comment by ipa-nhg** [comment]
for example, it can be the Readme of the setup repository, at the moment it is empty ( https://github.com/ipa320/setup/blob/master/README.md ). @ipa-fmw what do you think?

**Comment by ipa-mig** [comment]
Alright, let's wait for some more input/suggestions. Then I can move it.

**Comment by ipa-fmw** [comment]
+1 for using ipa320/setup readme for linking the document

**Comment by ipa-mig** [comment]
so should I put it AS the readme? A link ON the readme? I'm not sure I understand what you mean right now ;-)

**Comment by ipa-fmw** [comment]
I'd like to link it in the overall readme under coding guidelines not use it AS the readme. Clear now?

**Comment by ipa-mig** [comment]
@ipa-fmw, @ipa-nhg Done!

**Comment by ipa-nhg** [comment]
:+1:

**Comment by ipa-fxm** [comment]
Merging for now!
@ipa-mig did we already get feedback from the first students using it? Anything missing?

**Comment by ipa-mig** [comment]
Yup, some feedback was there. I integrated most of it directly.

Feedback I just received this week and haven't integrated yet was to include some "best practices" for `package.xml` and `CMakeLists.txt`.

Something along the lines of

- sort dependencies alphabetically
- for each target, have `add_executable/add_library`, `add_dependencies` and `target_link_libraries` directly after each other
- use `add_dependencies(TARGET ${${PROJECT_NAME}_EXPORTED_TARGETS}` and `add_dependencies(TARGET catkin_EXPORTED_TARGETS}` respectively.
- delete unnecessary comments out of the files
- ...

Maybe we should also add a condensed tl;dr version where the most important DO's and DONT's are mentionend, e.g. (greetings to @ipa-fxm ;-) ):

- Github user name should be `ipa-KÜRZEL`
- ...

**Pull request merged**
